# Generated by Django 5.1.4 on 2026-09-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "app_label",
                    models.CharField(
                        help_text="The app_name given to Templify during conversion.",
                        max_length=60,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether customers can pick this template for new sites.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="International format, e.g. 27821234567",
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="builder.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_path",
                    models.CharField(
                        help_text="Path inside the template zip, e.g. assets/css/main.css",
                        max_length=500,
                    ),
                ),
                ("file", models.FileField(upload_to="template_assets/")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="builder.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplatePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text='Empty string means this is the home page ("").',
                        max_length=80,
                    ),
                ),
                ("document", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="builder.template",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("template", "slug")},
            },
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Django template variable name, e.g. slot_12",
                        max_length=40,
                    ),
                ),
                ("default_text", models.TextField()),
                (
                    "label",
                    models.CharField(
                        help_text="Short preview shown in the editor, e.g. the enclosing tag + text.",
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="builder.templatepage",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="builder.template",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("template", "key")},
            },
        ),
        migrations.CreateModel(
            name="SiteSlotValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_values",
                        to="builder.site",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_values",
                        to="builder.templateslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "slot")},
            },
        ),
    ]
