# Generated by Django 5.1.4 on 2026-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(
                choices=[
                    ("shield", "Shield"),
                    ("wrench", "Wrench"),
                    ("clock", "Clock"),
                    ("star", "Star"),
                    ("check-circle", "Checkmark"),
                ],
                default="shield",
                max_length=20,
            ),
        ),
    ]
