# Generated by Django 5.1.4 on 2026-09-20 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer who can log into web-portal and edit this site's text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
