# Generated by Django 5.1.4 on 2026-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0002_site_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="package",
            field=models.CharField(
                blank=True,
                choices=[
                    ("starter", "Starter Site"),
                    ("growth", "Growth Hub"),
                    ("business_os", "Business OS"),
                ],
                help_text="Which paid package this site is on. Blank means the free tier (branded).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="payfast_token",
            field=models.CharField(
                blank=True,
                help_text="PayFast subscription token (for managing/cancelling recurring billing), set once the ITN confirms payment.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    (
                        "pending",
                        "Pending (checkout started, awaiting PayFast confirmation)",
                    ),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
