# Generated by Django 5.1.4 on 2026-09-20 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0004_customerauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="Hex override (e.g. #2e8b57) for the template's own detected accent color (Template.default_primary_color). Blank means use the template's default.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Enter a hex color like #2e8b57."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="default_primary_color",
            field=models.CharField(
                blank=True,
                help_text="This template's own dominant accent color, auto-detected at ingest (services.template_ingest._parametrize_theme_color) and rewritten into its CSS as var(--vicinic-primary, <this color>) — blank means none was confidently detected, so a Site's own primary_color override has nothing to hook into.",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9a-fA-F]{6}$", "Enter a hex color like #2e8b57."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Also where this site's own contact form (site_contact) sends messages.",
                max_length=254,
            ),
        ),
    ]
