# Generated by Django 5.1.4 on 2026-09-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0005_site_primary_color_template_default_primary_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="cloudflare_nameservers",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated — what the customer needs to set at their registrar for domain_status to become active.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="cloudflare_zone_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="site",
            name="custom_domain",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A customer-owned domain (e.g. mybusiness.com), connected via services.cloudflare — the customer points its nameservers at Cloudflare's, which turns it into a zone under Vicinic's own Cloudflare account.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="domain_status",
            field=models.CharField(
                choices=[
                    ("none", "Not connected"),
                    ("pending", "Pending (waiting for nameservers to update)"),
                    ("active", "Active"),
                    ("error", "Error"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                (
                    "to_address",
                    models.EmailField(
                        help_text="Where mail sent to from_address actually gets delivered.",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "pending_verification",
                                "Waiting on destination email verification",
                            ),
                            ("active", "Active"),
                            ("error", "Error"),
                        ],
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                ("cloudflare_rule_id", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_routes",
                        to="builder.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "from_address")},
            },
        ),
    ]
