# Generated by Django 5.1.4 on 2026-09-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "builder",
            "0006_site_cloudflare_nameservers_site_cloudflare_zone_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("cloudflare", "Cloudflare Registrar"),
                            ("hostafrica", "HostAfrica (.za)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the registrar itself charges Vicinic, in cost_currency.",
                        max_digits=10,
                    ),
                ),
                ("cost_currency", models.CharField(default="USD", max_length=3)),
                (
                    "price_zar",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the customer is actually charged (cost_amount converted to ZAR, plus DOMAIN_MARKUP_ZAR) — locked in at purchase time so a later exchange-rate change can't retroactively change what was agreed.",
                        max_digits=10,
                    ),
                ),
                ("registrant_name", models.CharField(max_length=200)),
                ("registrant_email", models.EmailField(max_length=254)),
                ("registrant_phone", models.CharField(max_length=30)),
                ("registrant_address_street", models.CharField(max_length=200)),
                ("registrant_address_city", models.CharField(max_length=100)),
                (
                    "registrant_address_state",
                    models.CharField(blank=True, max_length=100),
                ),
                ("registrant_address_postal_code", models.CharField(max_length=20)),
                (
                    "registrant_address_country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2, e.g. ZA", max_length=2
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Waiting on payment"),
                            ("paid", "Paid — registering"),
                            ("registered", "Registered"),
                            ("failed", "Failed"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        help_text="Set on STATUS_FAILED after payment already cleared — needs a human to reconcile (retry registration, or refund the customer via the PayFast dashboard).",
                        max_length=500,
                    ),
                ),
                ("payfast_m_payment_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_purchases",
                        to="builder.site",
                    ),
                ),
            ],
        ),
    ]
