# Generated by Django 5.1.4 on 2026-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0007_domainpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="ai_assistant_description",
            field=models.TextField(
                blank=True,
                help_text="What this business does, in the owner's own words — given to the AI chat widget as context so it can answer simple visitor questions without inventing details.",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="ai_assistant_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Shows a floating AI chat widget (services.ai_assistant) on this site's rendered pages, plus a WhatsApp chat link when whatsapp_number is set.",
            ),
        ),
    ]
