# Generated by Django 5.1.4 on 2026-09-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builder", "0008_site_ai_assistant_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="whatsapp_phone_number_id",
            field=models.CharField(
                blank=True,
                help_text="The connected number's phone_number_id within whatsapp_waba_id — this is what an inbound webhook payload's value.metadata.phone_number_id is matched against (whatsapp_views.whatsapp_webhook) to find which Site a message belongs to, and what services.whatsapp.send_message sends against.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="whatsapp_waba_id",
            field=models.CharField(
                blank=True,
                help_text="Meta WhatsApp Business Account ID, set once the owner connects their own number via Embedded Signup (customer_api.api_customer_whatsapp_connect) — a real in-WhatsApp AI bot on their own number, distinct from the wa.me link/on-site chat widget above.",
                max_length=50,
            ),
        ),
    ]
